[build]
compiler = "gcc"

[os]
name = "ruxos"
services = ["alloc","paging","fs","blkfs"]
ulib = "ruxlibc"

[os.platform]
name = "x86_64-qemu-q35"
smp = "4"
mode = "release"
log = "warn"

[os.platform.qemu]
graphic = "n"
blk = "y"

[[targets]]
name = "filetest"
src = "./"
include_dir = "./"
type = "exe"
cflags = ""
linker = "rust-lld -flavor gnu"
ldflags = ""
